global:
  enabled: true
  tlsDisable: true

injector:
  enabled: true

server:
  image:
    repository: "hashicorp/vault-enterprise"
    tag: "1.19.0-ent"
  
  enterpriseLicense:
    enabled: true
    secretName: "vault-license"
    secretKey: "license"
  
  extraVolumes:
    - type: secret
      name: vault-license
      path: /vault/license
  
  ha:
    enabled: false
  
  standalone:
    enabled: true
    config: |
      ui = true
      disable_mlock = true
      
      license_path = "/vault/license/license"
      
      listener "tcp" {
        address = "[::]:8200"
        tls_disable = true
      }
      
      storage "file" {
        path = "/vault/data"
      }

  dataStorage:
    enabled: true
    storageClass: "longhorn"
    size: "10Gi"

ui:
  enabled: true
  serviceType: "ClusterIP"
  publishNotReadyAddresses: true
  activeVaultPodOnly: false
  externalPort: 8200
  targetPort: 8200

csi:
  enabled: false

# Vault UI Ingress
ingress:
  enabled: true
  ingressClassName: nginx
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: vault.maniak.lab
      paths:
        - / 